/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2022-06-17 18:25:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import datosRatos.DatosEstatusCliente;
import entidad.EstatusClientes;
import entidad.UsuarioSistema;
import entidad.UsuarioTransitivo;
import utilidades.PerfilUsuario;

public final class estatus_005fclientes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/detectausuario.jsp", Long.valueOf(1599579422000L));
    _jspx_dependants.put("/despliega_menu.jsp", Long.valueOf(1606845630000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Efectivale - PLD</title>\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"widht=device-widht, user-scalable=no, initial-scale=1.0, minimun-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css\">\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Material Design Bootstrap **** -->\r\n");
      out.write("<link href=\"./css/mdb.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Your custom styles (optional) -->\r\n");
      out.write("<link href=\"./css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/forms.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/xlarge.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/large.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/medium.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/small.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/xsmall.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"startTimer(90)\">\r\n");
      out.write("\t<header id=\"header\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"row align-items-center pt-2 pb-2\">\r\n");
      out.write("\t\t\t\t<div class=\"col-12 col-sm-12 col-md-4 col-lg-2 col-xl-3\">\r\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" href=\"/\"> <img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"./img/logo-main.png\" width=\"398px\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"img-fluid float-left logo mr-auto\" style=\"maxwidth: 160px;\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Logo Efectivale\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-12 col-sm-12 col-md-5 col-lg-8 col-xl-7\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-12 header-contact-numbers\">\r\n");
      out.write("\t\t\t\t\t\t\t<h1 class=\"title title-contrata-ahora\">Sistema de Prevención\r\n");
      out.write("\t\t\t\t\t\t\t\tde Lavado de Dinero-code</h1>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<h5 class=\"title title-contrata-ahora white-text\">\r\n");
      out.write("\t\tSistema de Prevención de Lavado de Dinero\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"main row\">\r\n");
      out.write("\t\t\t\t<article class=\"col-xs-12 col-sm-8 col-md-9 col-lg-9\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"text-muted\">Estatus de clientes</h2>\r\n");
      out.write("\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t<aside class=\"col-xs-12 col-sm-4 col-md-3 col-lg-3\">\r\n");
      out.write("\t\t\t\t\t<p class=\"lead\">\r\n");
      out.write("\t\t\t\t\t\tBienvenido:\r\n");
      out.write("\t\t\t\t\t\t");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	if (request.getSession().getAttribute("usuario") != null) {
		try {

			if (request.getSession().getAttribute("tipo") != null
					&& request.getSession().getAttribute("tipo") == "T") {
				UsuarioTransitivo ut = (UsuarioTransitivo) request.getSession().getAttribute("usuario");
				String usuario = ut.getCliente().getCliente_Id();
				out.println(usuario);
			} else {
				
				////UsuarioSistema us = (Usuario Sistema)request.getSession().getAttribute("usuario") ;
				UsuarioSistema us = (UsuarioSistema) request.getSession().getAttribute("usuario");
				String usuario = us.getUsuario();
				out.println(usuario);
			}
		} catch (Exception es) {
			es.printStackTrace();
		}
	}

      out.write("\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</aside>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-9 table-responsive\">\r\n");
      out.write("\t\t\t\t <!-- en esta parte,estamos llamando al servlet que es control de busqueda -->\r\n");
      out.write("\t\t\t\t\t<form id=\"frmEstatus\" action=\"BusquedaEstatusCliente\" method=\"post\"\r\n");
      out.write("\t\t\t\t\t\tautocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"300px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"md-form form-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" onkeyup=\"mayus(this)\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"nombre\" name=\"nombre\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
String vNombre = (String) request.getAttribute("nombre");
			if (vNombre != null) {
				out.println(vNombre);
			}
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"nombre\">* Nombre</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div> <input type=\"hidden\" id=\"move_offset\" name=\"move_offset\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"50px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"300px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"md-form form-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" onkeyup=\"mayus(this)\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"rfc\" name=\"rfc\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
String vrfc = (String) request.getAttribute("rfc");
			if (vrfc != null) {
				out.println(vrfc);
			}
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"rfc\">* RFC</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"90px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"javascript:formSubmit('frmEstatus',0)\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"img/lupa.jpg\" width=\"32\" height=\"32\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"30px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"javascript:formSubmitXls('frmEstatus')\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"img/excel.png\" width=\"32\" height=\"32\" /> <!--<a href=\"javascript:Tabla2Excel('tblEstatusClientes', 'EstatusClientes')\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/excel.png\" width=\"32\" height=\"32\" />-->\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"md-form form-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" type=\"text\" onkeyup=\"mayus(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"idCliente\" name=\"idCliente\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
String vidCliente = (String) request.getAttribute("idCliente");
			if (vidCliente != null) {
				out.println(vidCliente);
			}
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"idCliente\">* Id Salesforce</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"50px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"md-form form-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" type=\"text\" onkeyup=\"mayus(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"noCliente\" name=\"noCliente\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
String vnoCliente = (String) request.getAttribute("noCliente");
			if (vnoCliente != null) {
				out.println(vnoCliente);
			}
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"noCliente\">* No Cliente</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><select class=\"browser-default\" id=\"tipoPersona\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"tipoPersona\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"\">* Tipo</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											String vtipoPersona;
											if (request.getAttribute("tipoPersona") == null)
												vtipoPersona = "";
											else
												vtipoPersona = (String) request.getAttribute("tipoPersona");

											if (vtipoPersona.compareTo("") != 0)
												out.println("<option value=''>Todos</option>)");
											else
												out.println("<option value='' selected='true'>Todos</option>)");

											if (vtipoPersona.compareTo("F") != 0)
												out.println("<option value='F'>Física</option>)");
											else
												out.println("<option value='F' selected='true'>Fisica</option>)");

											if (vtipoPersona.compareTo("M") != 0)
												out.println("<option value='M'>Moral</option>)");
											else
												out.println("<option value='M' selected='true'>Moral</option>)");

											if (vtipoPersona.compareTo("X") != 0)
												out.println("<option value='X'>Fideicomiso</option>)");
											else
												out.println("<option value='X' selected='true'>Fideicomiso</option>)");

											if (vtipoPersona.compareTo("G") != 0)
												out.println("<option value='G'>Gobierno</option>)");
											else
												out.println("<option value='G' selected='true'>Gobierno</option>)");
										
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"50px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><select class=\"browser-default\" id=\"estatus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"estatus\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"\">* Estatus</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											String vEstatusFiltro;
											if (request.getAttribute("estatus") == null)
												vEstatusFiltro = "";
											else
												vEstatusFiltro = (String) request.getAttribute("estatus");

											if (vEstatusFiltro.compareTo("") != 0)
												out.println("<option value=''>Todos</option>)");
											else
												out.println("<option value='' selected='true'>Todos</option>)");

											if (vEstatusFiltro.compareTo("S") != 0)
												out.println("<option value='S'>No iniciado</option>)");
											else
												out.println("<option value='S' selected='true'>No iniciado</option>)");

											if (vEstatusFiltro.compareTo("P") != 0)
												out.println("<option value='P'>Pendiente</option>)");
											else
												out.println("<option value='P' selected='true'>Pendiente</option>)");

											if (vEstatusFiltro.compareTo("V") != 0)
												out.println("<option value='V'>Por Validar</option>)");
											else
												out.println("<option value='V' selected='true'>Por Validar</option>)");

											if (vEstatusFiltro.compareTo("A") != 0)
												out.println("<option value='A'>Validado</option>)");
											else
												out.println("<option value='A' selected='true'>Validado</option>)");

											if (vEstatusFiltro.compareTo("I") != 0)
												out.println("<option value='I'>Invalido</option>)");
											else
												out.println("<option value='I' selected='true'>Invalido</option>)");

											if (vEstatusFiltro.compareTo("G") != 0)
												out.println("<option value='G'>Ventas Gobierno</option>)");
											else
												out.println("<option value='G' selected='true'>Ventas Gobierno</option>)");
											if (vEstatusFiltro.compareTo("N") != 0)
												out.println("<option value='N'>Inactivo</option>)");
											else
												out.println("<option value='N' selected='true'>Inactivo</option>)");
											if (vEstatusFiltro.compareTo("R") != 0)
													out.println("<option value='R'>Actualizar</option>)");
											else
											    out.println("<option value='R' selected='true'>Actualizar</option>)");
											
												
										
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><select class=\"browser-default\" id=\"bandera\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"bandera\">\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t<option value=\"\">Todos</option> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											String vBanderaFiltro;
											if (request.getAttribute("bandera") == null)
												vBanderaFiltro = "";
											else
												vBanderaFiltro = (String) request.getAttribute("bandera");

											if (vBanderaFiltro.compareTo("0") != 0)
												out.println("<option value=''>Todos</option>)");
											else
												out.println("<option value='' selected='true'>Todos</option>)");

											if (vEstatusFiltro.compareTo("1") != 0)
												out.println("<option value='1'>Riesgo</option>)");
											else
												out.println("<option value='1' selected='true'>Riesgo</option>)");
											
											if (vEstatusFiltro.compareTo("0") != 0)
													out.println("<option value='0'>Sin Riesgo</option>)");
											else
													out.println("<option value='0' selected='true'> Sin RiesgoRiesgo</option>)");
												
										
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t");
      out.write('\n');
      out.write('\n');

	HttpSession ses = request.getSession();
	if (ses != null && ses.getAttribute("perfilId") != null) {
		String perfil = ses.getAttribute("perfilId").toString();
		if (perfil != null && !perfil.isEmpty()) {
			if (perfil.equals(PerfilUsuario.Administrador)) {
				out.println("<a href=\"avisos.jsp\">Genera avisos</a><br>");
				out.println("<a href=\"bloqueo_masivo.jsp\">Mantenimiento</a><br>");
				out.println("<a href=\"estatus_clientes.jsp\">Estatus Clientes</a><br>");
				out.println("<a href=\"perfiles.jsp\">Perfiles</a><br>");
				out.println("<a href=\"prospectos.jsp\">Alta de prospectos</a><br>");
				out.println("<a href=\"usuarios.jsp\">Usuarios</a><br>");
				out.println("<a href=\"rep_pld.jsp\">Representantes Legales</a><br>");
				out.println("<a href=\"contrasena.jsp\">Cambio de contraseña</a><br>");
				out.println("<a href=\"DespliegaLog.jsp\">Logs</a><br>");
				out.println("<a href=\"logout.jsp\">Salir</a>");
			} else if (perfil.equals(PerfilUsuario.PLD)) {
				out.println("<a href=\"avisos.jsp\">Genera avisos</a><br>");
				out.println("<a href=\"prospectos.jsp\">Alta prospectos</a><br>");
				out.println("<a href=\"estatus_clientes.jsp\">Estatus Clientes</a><br>");
				out.println("<a href=\"contrasena.jsp\">Cambio de contraseña</a><br>");
				out.println("<a href=\"logout.jsp\">Salir</a>");
			} else if (perfil.equals(PerfilUsuario.SOPORTE)) {
				out.println("<a href=\"avisos.jsp\">Genera avisos</a><br>");
				out.println("<a href=\"prospectos.jsp\">Alta prospectos</a><br>");
				out.println("<a href=\"estatus_clientes.jsp\">Estatus Clientes</a><br>");
				out.println("<a href=\"contrasena.jsp\">Cambio de contraseña</a><br>");
				out.println("<a href=\"DespliegaLog.jsp\">Logs</a><br>");
				out.println("<a href=\"logout.jsp\">Salir</a>");
			} else if (perfil.equals(PerfilUsuario.Admin_Telemarketing)) {
				out.println("<a href=\"estatus_clientes.jsp\">Estatus Clientes</a><br>");
				out.println("<a href=\"prospectos.jsp\">Alta de prospectos</a><br>");
				out.println("<a href=\"usuarios.jsp\">Usuarios</a><br>");
				out.println("<a href=\"contrasena.jsp\">Cambio de contraseña</a><br>");
				out.println("<a href=\"logout.jsp\">Salir</a>");
			} else if (perfil.equals(PerfilUsuario.Supervisor)) {
				out.println("<a href=\"estatus_clientes.jsp\">Estatus Clientes</a><br>");
				out.println("<a href=\"prospectos.jsp\">Alta de prospectos</a><br>");
				out.println("<a href=\"contrasena.jsp\">Cambio de contraseña</a><br>");
				out.println("<a href=\"logout.jsp\">Salir</a>");
			} else if (perfil.equals(PerfilUsuario.Ejecutivo_de_ventas)) {
				out.println("<a href=\"estatus_clientes.jsp\">Estatus Clientes</a><br>");
				out.println("<a href=\"prospectos.jsp\">Alta de prospectos</a><br>");
				out.println("<a href=\"contrasena.jsp\">Cambio de contraseña</a><br>");
				out.println("<a href=\"logout.jsp\">Salir</a>");
			} else if (perfil.equals(PerfilUsuario.Cliente)) {
				//out.println("<a href=\"tipo_persona.jsp\">Capturar datos</a><br>");
				out.println("<a href=\"contrasena.jsp\">Cambio de contraseña</a><br>");
				out.println("<a href=\"logout.jsp\">Salir</a>");
			}

		} else {
			response.sendRedirect("logout.jsp");
		}

	} else {
		response.sendRedirect("logout.jsp");
	}

      out.write("\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<table class=\"table table-sm table-striped table-bordered table-hover table-condensed\"\r\n");
      out.write("\t\t\t\tid=\"tblEstatusClientes\" name=\"tblEstatusClientes\">\r\n");
      out.write("\t\t\t\t<tr class=\"info\">\r\n");
      out.write("\t\t\t\t\t<th>Id Sales Force</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<th width=\"10%\" >Id Cliente</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"10%\">Nombre</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"10%\">RFC</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"5%\">Tipo</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"5%\">Estatus</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"10%\">Validó</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"10%\">Fecha de validación</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"10%\">Fecha de bloqueo</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"10%\">Fecha ult. mod.</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"10%\">Mensaje</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"10%\">Notas</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"10%\">Ejecutivo</th>\r\n");
      out.write("                <th width=\"10%\">Coincidencia en listas</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					int OFFSET_VALUE = 50;
					String where = "";
					String usuario = "";
					String IdPerfil = "";
					String Offset = "";

					try {
						where = (String) request.getAttribute("where");
						Offset = (String) request.getAttribute("offset");
					} catch (Exception es) {
						es.printStackTrace();
					}

					if (Offset == null) {
						Offset = "0";
					}
					//Recuperando el usuario autenticado
					try {
						HttpSession sesion = request.getSession();
						usuario = sesion.getAttribute("user").toString();
						IdPerfil = sesion.getAttribute("perfilId").toString();

					} catch (Exception es) {
						es.printStackTrace();
					}

					//EstatusClientes[] c = new DatosEstatusCliente().getList(where, usuario, IdPerfil);
					EstatusClientes[] c = null;
					if (where != null) {
						c = new DatosEstatusCliente().getList(where, usuario, IdPerfil, Offset);
					}
					if (c != null) {

						for (int i = 0; i < c.length; i++) {

							String servlet = "";
							if (c[i].getTipoPersona().trim().equals("F")) {
								servlet = "EdicionPersonaFisica";
							} else if (c[i].getTipoPersona().trim().equals("M")) {
								servlet = "EdicionPersonaMoral";
							} else if (c[i].getTipoPersona().trim().equals("X")) {
								servlet = "EdicionFideicomiso";
							} else if (c[i].getTipoPersona().trim().equals("G")) {
								servlet = "EdicionGobierno";
							} else {
								servlet = "tipo_persona.jsp";
							}

							out.println("<tr>");
							out.println("<td><a href=\"" + servlet + "?idCliente=" + c[i].getClienteId().trim()
									+ "&esVerificacion=1&rfc=" + c[i].getRfc().trim().replace("&", "%26")
									+ "\" style=\"text-decoration: underline; color:blue;\">" + c[i].getClienteId() + "</a>");
							out.println("</td>");

							out.println("<td>" + c[i].getIdClienteNumerico());
							out.println("</td>");

							//<td><a href="verificacion.html">A-12345</a>
							//</td>					
							out.println("<td>" + c[i].getRazonSocial());
							out.println("</td>");
							out.println("<td>" + c[i].getRfc());
							out.println("</td>");
							out.println("<td>" + c[i].getTipoPersona());
							out.println("</td>");
							out.println("<td>" + c[i].getEstatus());
							out.println("</td>");
							out.println("<td>" + c[i].getUsuariovalido());
							out.println("</td>");
							out.println("<td>" + c[i].getFechaValido());
							out.println("</td>");
							out.println("<td>" + c[i].getFechaBloqueo());
							out.println("</td>");
							out.println("<td>" + c[i].getFechaModificacion());
							out.println("</td>");
							out.println("<td>" + c[i].getMensaje());
							out.println("</td>");
							out.println("<td>" + c[i].getNotas());
							out.println("</td>");
							out.println("<td>" + c[i].getEjecutivo());
							out.println("</td>");
							out.println("<td>");
							
							   if (c[i].getRiesgo() == 1 ){
							  	 out.println("<img src='img/checked.png' height='32' width='32'>");
							    }else{
							     out.println("<img src='img/no_checked.png' height='32' width='32'>");
							    }
							   
							out.println("</td>");
							out.println("</tr>");

						} //fin del for
						
						
						
						out.println("</table> ");
						out.println("<input type=" + (char) 34 + "hidden" + (char) 34 + " id=" + (char) 34 + "offset"
								+ (char) 34 + " name=" + (char) 34 + "offset" + (char) 34 + " value=" + (char) 34 + Offset
								+ (char) 34 + ">");
						// Pintar el retroceso
						if (Integer.parseInt(Offset) >= OFFSET_VALUE) {
							out.println("<a href=" + (char) 34 + "javascript:formSubmit('frmEstatus',-" + OFFSET_VALUE + ")"
									+ (char) 34 + "><img src='img/PREV.png' width='18' height='32' /></a>");
							//out.println("<input type='button' value='<' onclick=" + (char)34 + "javascript:formSubmit('frmEstatus', -" + OFFSET_VALUE + ")" + (char)34 + "> ");
						}

						out.println("<label>Del registro " + Offset + " al "
								+ Integer.toString(Integer.parseInt(Offset) + c.length) + "</label>");
						if ((c.length > (OFFSET_VALUE - 1))) {
							out.println("<a href=" + (char) 34 + "javascript:formSubmit('frmEstatus'," + OFFSET_VALUE + ")"
									+ (char) 34 + "><img src='img/SIG.png' width='18' height='32' /></a>");
							//out.println("<input type='button' value='>' onclick=" + (char)34 + "javascript:formSubmit('frmEstatus', " + OFFSET_VALUE + ")" + (char)34 + "> ");
						}
					} else {
						out.println("</table> ");
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<footer>\r\n");
      out.write("\t\t\t\t\t<div class=\"row footer-menu-bottom\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>Todos los Derechos Reservados Efectivale S. de R.L</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"http://www.efectivale.com/comunicados/comunicado_LAAT.htm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttarget=\"_top\"> Disposiciones Vigentes de la LAAT </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"http://www.efectivale.com.mx/avisos/avisos_de_privacidad.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttarget=\"_top\"> Aviso de Privacidad </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"http://www.efectivale.com.mx/terminos/TCGCLIENTESDespensa-Comida.pdf\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttarget=\"_top\"> Términos y Condiciones </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</footer>\r\n");
      out.write("\t\t\t\t<script src=\"js/jquery.js\"></script>\r\n");
      out.write("\t\t\t\t<script src=\"js/validaciones.js\"></script>\r\n");
      out.write("\t\t\t\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t\t\t<script src=\"js/mdb.min.js.descarga\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tfunction formSubmit(formulario, move_offset) {\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('move_offset').value = move_offset;\r\n");
      out.write("\t\t\t\t\t\tvar SentForm = document.getElementById(formulario);\r\n");
      out.write("\t\t\t\t\t\tSentForm.action = \"BusquedaEstatusCliente\";\r\n");
      out.write("\t\t\t\t\t\tSentForm.target = \"\";\r\n");
      out.write("\t\t\t\t\t\tSentForm.submit();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tfunction formSubmitXls(formulario) {\r\n");
      out.write("\t\t\t\t\t\tvar SentForm = document.getElementById(formulario);\r\n");
      out.write("\t\t\t\t\t\tSentForm.action = \"XlsEstatusCliente\";\r\n");
      out.write("\t\t\t\t\t\t//                var w = window.open('about:blank','Popup_Window','toolbar=0,scrollbars=0,location=0,statusbar=0,menubar=0,resizable=0,width=400,height=300,left = 312,top = 234');                \r\n");
      out.write("\t\t\t\t\t\t//                SentForm.target=\"Popup_Window\";\r\n");
      out.write("\t\t\t\t\t\tSentForm.submit();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tvar Tabla2Excel = (function() {\r\n");
      out.write("\t\t\t\t\t\tvar uri = 'data:application/vnd.ms-excel;base64,', template = '<html xmlns:o=\"urn:schemas-microsoft-com:office:office\" xmlns:x=\"urn:schemas-microsoft-com:office:excel\" xmlns=\"http://www.w3.org/TR/REC-html40\"><head><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>{table}</table></body></html>', base64 = function(\r\n");
      out.write("\t\t\t\t\t\t\t\ts) {\r\n");
      out.write("\t\t\t\t\t\t\treturn window.btoa(unescape(encodeURIComponent(s)))\r\n");
      out.write("\t\t\t\t\t\t}, format = function(s, c) {\r\n");
      out.write("\t\t\t\t\t\t\treturn s.replace(/{(\\w+)}/g, function(m, p) {\r\n");
      out.write("\t\t\t\t\t\t\t\treturn c[p];\r\n");
      out.write("\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\treturn function(table, nombre) {\r\n");
      out.write("\t\t\t\t\t\t\tif (!table.nodeType)\r\n");
      out.write("\t\t\t\t\t\t\t\ttable = document.getElementById(table)\r\n");
      out.write("\t\t\t\t\t\t\tvar ctx = {\r\n");
      out.write("\t\t\t\t\t\t\t\tworksheet : nombre || 'Worksheet',\r\n");
      out.write("\t\t\t\t\t\t\t\ttable : table.innerHTML\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\twindow.location.href = uri\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ base64(format(template, ctx))\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t})();\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tvar txtExito = document.getElementById('exito').value;\r\n");
      out.write("\t\t\t\t\tvar txtRespuesta = document.getElementById('respuesta').value;\r\n");
      out.write("\t\t\t\t\tif (txtExito == '1' && txtRespuesta.length > 0) {\r\n");
      out.write("\t\t\t\t\t\talert(txtRespuesta);\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('exito').value = '0';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
