/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2022-06-17 15:52:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import datosRatos.XlsEstatusCliente;
import entidad.EstatusClientes;

public final class estatus_005fclientes_005fxls_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("application/vnd.ms-excel; charset=Unicode");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("﻿﻿\r\n");
      out.write("\r\n");
      out.write("\r\n");
      response.setHeader("Content-Disposition", "attachment;filename=EstatusClientes.xls");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head >\r\n");
      out.write("    <title>Efectivale - PLD</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header id=\"header\">\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<h5 >Sistema de Prevención de Lavado de Dinero</h1>\r\n");
      out.write("\t\t\t<table id=\"tblEstatusClientes\" name=\"tblEstatusClientes\">\r\n");
      out.write("\t\t\t\t<tr class=\"info\" >\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\tId Sales Force \r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("                                        \r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\tId Cliente\r\n");
      out.write("\t\t\t\t\t</th>\t\t\t\t\t\r\n");
      out.write("                                        \r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\tNombre\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\tRFC\r\n");
      out.write("\t\t\t\t\t</th>\t\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\tTipo\r\n");
      out.write("\t\t\t\t\t</th>\t\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\tEstatus\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\tValidó\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\tFecha de validación\r\n");
      out.write("\t\t\t\t\t</th>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\tFecha de bloqueo\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\tFecha ult. mod.\r\n");
      out.write("\t\t\t\t\t</th>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\tMensaje\r\n");
      out.write("\t\t\t\t\t</th>\t\r\n");
      out.write("                                        <th>\r\n");
      out.write("\t\t\t\t\t\tNotas\r\n");
      out.write("\t\t\t\t\t</th>\t\r\n");
      out.write("\t\t\t\t\t<th>Ejecutivo</th>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                \r\n");
      out.write("                                ");

                                    
                                    String where ="";
                                    String usuario = "";
                                    String IdPerfil = "";
                                    String Offset = "";
                                    
                                        try{
                                            where = (String)request.getAttribute("where");
                                            Offset = (String)request.getAttribute("offset");                                            
                                        } catch ( Exception es ){
                                            es.printStackTrace();
                                        }
                                        
                                        if (Offset==null) {
                                            Offset = "0";
                                        }                                        
                                        //Recuperando el usuario aitenticado
                                        try{
                                            HttpSession sesion = request.getSession();
                                            usuario = sesion.getAttribute("user").toString();
                                            IdPerfil = sesion.getAttribute("perfilId").toString();
                                            
                                        } catch ( Exception es ){
                                            es.printStackTrace();
                                        }
                                        
                                        
                                        //EstatusClientes[] c = new DatosEstatusCliente().getList(where, usuario, IdPerfil);
                                        EstatusClientes[] c =null;
                                        if(where!=null)
                                        {
                                            c=new XlsEstatusCliente().getList(where, usuario, IdPerfil);
                                        }
                                        if ( c != null){
                                            
                                            
                                           
                                            
                                            
                                            for (int i = 0; i < c.length; i++ ) 
                                            {
                                                
                                                String servlet = "";
                                                if ( c[i].getTipoPersona().trim().equals("F")){
                                                    servlet="EdicionPersonaFisica";
                                                } else if ( c[i].getTipoPersona().trim().equals("M")){
                                                    servlet="EdicionPersonaMoral";
                                                } else if ( c[i].getTipoPersona().trim().equals("X")){
                                                    servlet ="EdicionFideicomiso";
                                                } else if ( c[i].getTipoPersona().trim().equals("G")){
                                                    servlet = "EdicionGobierno";
                                                } else {
                                                    servlet = "tipo_persona.jsp";
                                                }
                                                
                                           
                                                
                                                out.println("<tr>");
                                                out.println("<td><a href=\"" + servlet + "?idCliente=" + c[i].getClienteId().trim() + "&esVerificacion=1&rfc=" + c[i].getRfc().trim().replace("&", "%26") + "\" style=\"text-decoration: underline; color:blue;\">" + c[i].getClienteId() + "</a>");
                                                out.println("</td>");
                                                
                                                out.println("<td>" + c[i].getIdClienteNumerico() );
                                                out.println("</td>");

                                                        //<td><a href="verificacion.html">A-12345</a>
                                                        //</td>					
                                                out.println("<td>" + c[i].getRazonSocial());
                                                out.println("</td>");
                                                out.println("<td>" + c[i].getRfc());
                                                out.println("</td>");
                                                out.println("<td>" + c[i].getTipoPersona());
                                                out.println("</td>");
                                                out.println("<td>" + c[i].getEstatus());
                                                out.println("</td>");
                                                out.println("<td>" + c[i].getUsuariovalido() );
                                                out.println("</td>");
                                                out.println("<td>" + c[i].getFechaValido() );
                                                out.println("</td>");
                                                out.println("<td>" + c[i].getFechaBloqueo() );
                                                out.println("</td>");
                                                out.println("<td>" + c[i].getFechaModificacion() );
                                                out.println("</td>");
                                                out.println("<td>" + c[i].getMensaje());
                                                out.println("</td>");
                                                out.println("<td>" + c[i].getNotas());
                                                out.println("</td>");
                                                out.println("<td>" + c[i].getEjecutivo());
                    							out.println("</td>");
                    							
                                                out.println("</tr>");

                                            } //fin del for
                                            out.println("</table> ");                    
                                        } else {
                                            out.println("</table> ");                                                                                
                                        }      
                                
      out.write("\r\n");
      out.write("\t<footer>\r\n");
      out.write("\r\n");
      out.write("</footer>\t\r\n");
      out.write("        <script>\r\n");
      out.write("            //Tabla2Excel('tblEstatusClientes', 'EstatusClientes');       \r\n");
      out.write("            window.close();\r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
