/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2022-06-16 20:54:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Efectivale - PLD</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"widht=device-widht, user-scalable=no, initial-scale=1.0, minimun-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css\">\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Material Design Bootstrap **** -->\r\n");
      out.write("<link href=\"./css/mdb.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Your custom styles (optional) -->\r\n");
      out.write("<link href=\"./css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/forms.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/xlarge.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/large.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/medium.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/small.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/xsmall.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction validarFormulario() {\r\n");
      out.write("\t\tvar txtUsuario = document.getElementById('usuario').value;\r\n");
      out.write("\t\tvar txtContrasena = document.getElementById('contrasena').value;\r\n");
      out.write("\r\n");
      out.write("\t\tif (txtUsuario == null || txtUsuario.length == 0\r\n");
      out.write("\t\t\t\t|| /^\\s+$/.test(txtUsuario)) {\r\n");
      out.write("\t\t\talert('Debe ingresar un usuario')\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (txtContrasena == null || txtContrasena.length == 0\r\n");
      out.write("\t\t\t\t|| /^\\s+$/.test(txtContrasena)) {\r\n");
      out.write("\t\t\talert('Debe ingresar una contraseña')\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header id=\"header\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"row align-items-center pt-2 pb-2\">\r\n");
      out.write("\t\t\t\t<div class=\"col-12 col-sm-12 col-md-4 col-lg-2 col-xl-3\">\r\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" href=\"/\"> <img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"./img/logo-main.png\" width=\"398px\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"img-fluid float-left logo mr-auto\" style=\"maxwidth: 160px;\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Logo Efectivale\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-12 col-sm-12 col-md-5 col-lg-8 col-xl-7\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-12 header-contact-numbers\">\r\n");
      out.write("\t\t\t\t\t\t\t<h1 class=\"title title-contrata-ahora\">Sistema de Prevención\r\n");
      out.write("\t\t\t\t\t\t\t\tde Lavado de Dinero-iniciando pruebas</h1>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<h1 class=\"title title-contrata-ahora white-text\">Sistema de\r\n");
      out.write("\t\tPrevención de Lavado de Dinero</h1>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"main row\">\r\n");
      out.write("\t\t\t<article class=\"col-xs-12 col-sm-8 col-md-9 col-lg-9\">\r\n");
      out.write("\t\t\t\t<h2 class=\"text-muted\">Inicio de sesión</h2>\r\n");
      out.write("\t\t\t\t<br> <label>Si usted ya es cliente de Efectivale e\r\n");
      out.write("\t\t\t\t\tingresa por primera vez, el usuario será su RFC y la contraseña el\r\n");
      out.write("\t\t\t\t\tnúmero de cliente (sin consignatarios).</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</article>\r\n");
      out.write("\t\t\t<aside class=\"col-xs-12 col-sm-4 col-md-3 col-lg-3\">\r\n");
      out.write("\t\t\t\t<p class=\"lead\"></p>\r\n");
      out.write("\t\t\t</aside>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-9 table-responsive\">\r\n");
      out.write("\t\t\t\t<form onsubmit=\"return validarFormulario()\" name=\"frmLogin\"\r\n");
      out.write("\t\t\t\t\tid=\"frmLogin\" action=\"login\" method=\"post\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<br> <input type=\"hidden\" name=\"respuesta\" id=\"respuesta\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\" /> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\tname=\"exito\" id=\"exito\" value=\"");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"5\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"md-form form-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input class=\"form-control\" type=\"text\" onkeyup=\"mayus(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"usuario\" id=\"usuario\" value=\"\"> <label\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfor=\"usuario\">* Usuario</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"30px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Descarga Manual\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"https://www.efectivale.com.mx/aml/MANUALES/Manual_PLD_CLIENTE_2019_v0005.pdf\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttarget=\"_blank\"><img src=\"img/descargar.png\" widht=\"32\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\theight=\"32\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"30px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<!--<td>Descarga Manual</br><a href=\"https://www.efectivale.com.mx/aml/MANUALES/PLD_Persona_Moral_2018.pdf\" target=\"_blank\"><img src=\"img/descargar.png\" widht=\"32\" height=\"32\" /></a></td>-->\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"md-form form-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input class=\"form-control\" type=\"password\" name=\"contrasena\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"contrasena\" value=\"\" maxlength=\"9\"> <label\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfor=\"contrasena\">* Contraseña</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"30px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Manual para el alta de Prospectos/Clientes</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"30px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<!--<td>Prevención Lavado de Dinero (Persona Moral)</td>-->\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a href=\"recuperar_password.jsp\">¿Olvidaste la\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcontraseña?</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-danger\">Aceptar</button>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div class=\"row footer-menu-bottom\">\r\n");
      out.write("\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>Todos los Derechos Reservados Efectivale S. de R.L</li>\r\n");
      out.write("\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\thref=\"http://www.efectivale.com/comunicados/comunicado_LAAT.htm\"\r\n");
      out.write("\t\t\t\t\t\ttarget=\"_top\"> Disposiciones Vigentes de la LAAT </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\thref=\"http://www.efectivale.com.mx/avisos/avisos_de_privacidad.html\"\r\n");
      out.write("\t\t\t\t\t\ttarget=\"_top\"> Aviso de Privacidad </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\thref=\"http://www.efectivale.com.mx/terminos/TCGCLIENTESDespensa-Comida.pdf\"\r\n");
      out.write("\t\t\t\t\t\ttarget=\"_top\"> Términos y Condiciones </a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>Versión 1.3.11</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<script src=\"js/jquery.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/mdb.min.js.descarga\"></script>\r\n");
      out.write("\t<script src=\"js/validaciones.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar txtExito = document.getElementById('exito').value;\r\n");
      out.write("\t\tvar txtRespuesta = document.getElementById('respuesta').value;\r\n");
      out.write("\t\tif (txtExito == '1' && txtRespuesta.length > 0) {\r\n");
      out.write("\t\t\talert(txtRespuesta);\r\n");
      out.write("\t\t\tdocument.getElementById('exito').value = '0';\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /login.jsp(92,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resultado}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent(null);
    // /login.jsp(93,37) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exito}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }
}
